name: Deploy Neurofit
on: 
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy on Vercel
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    environment:
      name: production
    concurrency:
      group: vercel-${{ github.ref }}
      cancel-in-progress: false
    env:
      VERCEL_USER_ID: ${{ secrets.VERCEL_USER_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npx vercel --prod --token $VERCEL_TOKEN --confirm